/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'care' at '11/29/16 10:00 AM' with Gradle 2.14.1
 *
 * @author care, @date 11/29/16 10:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
